package combat.manager;

import combat.actors.CombatPlayer;
import combat.items.Weapon;
import combat.ship.Room;
import javafx.util.Pair;

import java.util.List;

@SuppressWarnings("FieldCanBeLocal")
public class CombatManager {
    private CombatPlayer player;
    private CombatPlayer enemy;
    private Boolean isPlayersTurn;

    public CombatManager(CombatPlayer player, CombatPlayer enemy) {
        this.player = player;
        this.enemy = enemy;
        this.isPlayersTurn = true;
    }

    /**
     * Controls the whole process of combat from start to entering minigame.
     */
    public void enterCombat() {
    }

    /**
     * Controls process of deciding what happened after a player took their turn.
     *
     * @param attackReport STORM report generated by CombatActor which tells the game which weapons were fired and at which
     *                     rooms. Eg: [[Helm, Cannon1],[Sails, Cannon3]]
     * @return damageReport - STORM report detailing which rooms were hit and for how much damage. See CombatActor >
     * takeTurn() for its use and more info.
     */
    List<Pair<Room, Integer>> applyTurn(List<Pair<Room, Weapon>> attackReport) {
        return null;
    }

    /**
     * Ends the fight and starts minigame.
     */
    private void endCombat() {
    }
}